# Generated by Django 3.1.3 on 2021-08-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210616_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unique_name',
        ),
    ]
