# Generated by Django 3.1.3 on 2021-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('N', 'Not specified'), ('F', 'Female'), ('M', 'Male')], default='Not specified', max_length=2),
        ),
    ]
